### ISSUE TITLE
Is there a way to include light themes as well?

### ISSUE THREAD

**Issue by Eagle1337** [overdodactyl/ShadowFox#165] opened 2018-06-13 00:27 UTC
I don't know how to edit it myself to make the dark theme apply, The theme i want to use i Just want it's image from the persona theme thing and the rest to be shadowfox.

**Comment by overdodactyl** [comment] 2018-06-13 20:42
Hi @Eagle1337, it sounds like you are trying to apply ShadowFox in combination with another theme available in the add-on store or something of that nature?

Currently there isn't a great way to do so - ShadowFox is mainly meant to be used in conjunction with the default dark theme Mozilla provides (doing so prevents needing to re-style thing, makes it easier to keep up with their changes, smaller likelihood of breakage etc).

If you're only looking to apply an image, it might be possible to do that without relying on a third party theme.  If you want to link me to what you are trying to apply, or something similar, I can give it a look when I have some time.

**Comment by Eagle1337** [comment] 2018-06-14 02:31
[The Theme](https://addons.mozilla.org/en-US/firefox/addon/non-non-biyori/?src=search)
It look like mozilla has changed things so the only thing that isn't dark now is the search bar and search suggestions.

**Comment by overdodactyl** [comment] 2018-07-15 22:12
Hi @Eagle1337, I haven't found a great way to add images as a background. You might try asking over at http://reddit.com/r/firefoxcss to see if anyone can help out.  

I'm going to close this for now as it's a little out of purpose for ShadowFox, but if I run across a method to do what you are looking for I'll let you know.

**Closed by overdodactyl** 2018-07-15 22:12 UTC

**Comment by seascape** [comment] 2018-11-16 05:20
I have been trying to do this too and will share my observations. 

I run 3 Firefox installations (well, one installed, and two portable) and they all have unique add-on themes (what used to be called personas) to visually differentiate them. My Shadowfox installation is 8 months old so I went to update it today but found that it conflicted with any theme outside the dark. By design, which is fair. Unfortunate for my use case though.

Here's an example of it messing up the new tab page (the "config" gear in the corner is also wrong):

OK, with the supported built-in Dark theme:
![screenclip 3](https://user-images.githubusercontent.com/1672115/48598512-15430200-e918-11e8-87cc-77309b2ecadc.png)

text color error with themes from FF add-ons ("Dark Fox" in this case):
![screenclip 4](https://user-images.githubusercontent.com/1672115/48598517-17a55c00-e918-11e8-81a0-4f2a7e939a43.png)

Another problem is the Customize Toolbar screen has a light background.

I can find no way to edit Firefox's built-in Dark theme to change the header/footer images it uses, which would solve my unique-themed browser issue. Also, trying to edit the exposed colors of an add-on theme like "Dark Fox" via about:config's lightweightThemes.usedThemes yielded no discernible changes.

It would be nice if there were a color setting or two somewhere in the ShadowFox files that I could tweak to correct the above-noted issues with third-party themes, but I'm not sure it'd be so simple?

**Comment by overdodactyl** [comment] 2018-11-16 15:48
@seascape, I'll look into what it would take to provide extra styling for other non-dark themes.

>It would be nice if there were a color setting or two somewhere in the ShadowFox files that I could tweak to correct the above-noted issues with third-party themes, but I'm not sure it'd be so simple?

One easy way would be to add your own custom rules to `userContent_customization.css`:

https://github.com/overdodactyl/ShadowFox/wiki/Customization
