### ISSUE TITLE
Library isn't dark themed.

### ISSUE THREAD

**Issue by xAphex** [overdodactyl/ShadowFox#29] opened 2017-12-14 20:18 UTC
the Library (downloads/bookmarks/history) isn't dark themed.
# [Image](https://image.prntscr.com/image/XbNBwmufTnS7KlqhJDgU4g.png)

**Comment by overdodactyl** [comment] 2017-12-14 20:20
Duplicate of #23 - it's a work in progress

**Closed by overdodactyl** 2017-12-14 20:20 UTC
